package com.example.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.model.TransactionEntity
import com.example.ui.viewmodel.CategoryShare
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Utility to generate and share visual financial analytics:
 * 1. Formatted visual text summary ready for WhatsApp, Telegram, and Messages.
 * 2. High-resolution graphical PNG report card generated via Android Canvas.
 */
object VisualAnalyticsExporter {

    /**
     * Formats a clean, emoji-rich summary text ready to send directly to WhatsApp or others.
     */
    fun generateShareableSummaryText(
        periodLabel: String,
        totalIncome: Double,
        totalExpense: Double,
        netBalance: Double,
        topCategories: List<CategoryShare>,
        avgDailyExpense: Double,
        txCount: Int
    ): String {
        val savingsRate = if (totalIncome > 0) ((netBalance / totalIncome) * 100).coerceIn(-100.0, 100.0) else 0.0
        val sb = StringBuilder()

        sb.append("📊 *KHARCH FINANCIAL ANALYTICS*\n")
        sb.append("🗓 *Period:* $periodLabel\n")
        sb.append("━━━━━━━━━━━━━━━━━━━━━━━━━\n\n")

        sb.append("💰 *Total Income:*  +Rs. ${String.format(Locale.getDefault(), "%,.0f", totalIncome)}\n")
        sb.append("💸 *Total Expenses:* -Rs. ${String.format(Locale.getDefault(), "%,.0f", totalExpense)}\n")
        sb.append("📈 *Net Balance:*   ${if (netBalance >= 0) "+Rs. " else "-Rs. "}${String.format(Locale.getDefault(), "%,.0f", kotlin.math.abs(netBalance))}\n")
        if (totalIncome > 0) {
            sb.append("🎯 *Savings Rate:*  ${String.format(Locale.getDefault(), "%.1f", savingsRate)}%\n")
        }
        sb.append("\n━━━━━━━━━━━━━━━━━━━━━━━━━\n")
        sb.append("🏷 *TOP SPENDING CATEGORIES:*\n")

        if (topCategories.isEmpty()) {
            sb.append("• No expense records for this period\n")
        } else {
            topCategories.take(5).forEachIndexed { idx, cat ->
                val bar = getEmojiBar(cat.percentage)
                sb.append("${idx + 1}. *${cat.category}*: Rs. ${String.format(Locale.getDefault(), "%,.0f", cat.amount)} (${String.format(Locale.getDefault(), "%.1f", cat.percentage)}%)\n")
                sb.append("   $bar\n")
            }
        }

        sb.append("\n━━━━━━━━━━━━━━━━━━━━━━━━━\n")
        sb.append("📅 *Daily Avg:* Rs. ${String.format(Locale.getDefault(), "%,.0f", avgDailyExpense)} · *Total Transactions:* $txCount\n")
        sb.append("⚡ _Generated by Kharch Personal Finance Vault_")

        return sb.toString()
    }

    private fun getEmojiBar(percentage: Number): String {
        val blocks = (percentage.toDouble() / 10).toInt().coerceIn(1, 10)
        return "🟩".repeat(blocks) + "⬜".repeat(10 - blocks)
    }

    /**
     * Creates a high-resolution 1000x1200 graphical PNG report image of the analytics.
     */
    fun createVisualAnalyticsImage(
        context: Context,
        periodLabel: String,
        totalIncome: Double,
        totalExpense: Double,
        netBalance: Double,
        topCategories: List<CategoryShare>,
        avgDailyExpense: Double,
        txCount: Int
    ): File {
        val width = 1080
        val height = 1350
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        // Background dark gradient fill
        val bgPaint = Paint().apply {
            color = Color.parseColor("#08101E")
        }
        canvas.drawRect(0f, 0f, width.toFloat(), height.toFloat(), bgPaint)

        // Accent top banner
        val bannerPaint = Paint().apply {
            color = Color.parseColor("#0A1E14")
        }
        canvas.drawRect(0f, 0f, width.toFloat(), 180f, bannerPaint)

        val borderPaint = Paint().apply {
            color = Color.parseColor("#00FFA3")
            strokeWidth = 4f
            style = Paint.Style.STROKE
        }
        canvas.drawLine(0f, 180f, width.toFloat(), 180f, borderPaint)

        // Header Title
        val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#00FFA3")
            textSize = 42f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        canvas.drawText("KHARCH · FINANCIAL ANALYTICS", 60f, 90f, titlePaint)

        val subPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#A0AEC0")
            textSize = 28f
        }
        canvas.drawText("Period: $periodLabel · Generated: ${SimpleDateFormat("MMM dd, yyyy", Locale.getDefault()).format(Date())}", 60f, 140f, subPaint)

        // 3 Key Metric Cards (Income, Expense, Net)
        val cardBgPaint = Paint().apply {
            color = Color.parseColor("#111C2E")
        }
        val cardBorder = Paint().apply {
            color = Color.parseColor("#1F304A")
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }

        // Draw Income Box
        drawMetricBox(
            canvas = canvas,
            rect = RectF(60f, 220f, 510f, 370f),
            label = "TOTAL INCOME",
            value = "+Rs. ${String.format(Locale.getDefault(), "%,.0f", totalIncome)}",
            valueColor = Color.parseColor("#10B981"),
            bgPaint = cardBgPaint,
            borderPaint = cardBorder
        )

        // Draw Expense Box
        drawMetricBox(
            canvas = canvas,
            rect = RectF(570f, 220f, 1020f, 370f),
            label = "TOTAL EXPENSES",
            value = "-Rs. ${String.format(Locale.getDefault(), "%,.0f", totalExpense)}",
            valueColor = Color.parseColor("#F43F5E"),
            bgPaint = cardBgPaint,
            borderPaint = cardBorder
        )

        // Draw Net Balance Box
        val netColor = if (netBalance >= 0) Color.parseColor("#00FFA3") else Color.parseColor("#F43F5E")
        val netSign = if (netBalance >= 0) "+Rs. " else "-Rs. "
        val savingsPercent = if (totalIncome > 0) ((netBalance / totalIncome) * 100).coerceIn(-100.0, 100.0) else 0.0
        drawMetricBox(
            canvas = canvas,
            rect = RectF(60f, 400f, 1020f, 530f),
            label = "NET CASH FLOW (SAVINGS RATE: ${String.format(Locale.getDefault(), "%.1f", savingsPercent)}%)",
            value = "$netSign${String.format(Locale.getDefault(), "%,.0f", kotlin.math.abs(netBalance))}",
            valueColor = netColor,
            bgPaint = cardBgPaint,
            borderPaint = cardBorder
        )

        // Top Spending Categories Section
        val sectionHeaderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.WHITE
            textSize = 34f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        canvas.drawText("TOP SPENDING CATEGORIES", 60f, 600f, sectionHeaderPaint)

        var currentY = 660f
        val catNamePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#E2E8F0")
            textSize = 28f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val catAmtPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.WHITE
            textSize = 28f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.RIGHT
        }
        val barBgPaint = Paint().apply {
            color = Color.parseColor("#1B293E")
        }

        val colors = listOf("#00FFA3", "#00E5FF", "#6366F1", "#F59E0B", "#F43F5E")

        if (topCategories.isEmpty()) {
            val emptyPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                color = Color.parseColor("#718096")
                textSize = 26f
            }
            canvas.drawText("No categorized expenses recorded in this period", 60f, currentY + 40f, emptyPaint)
            currentY += 120f
        } else {
            topCategories.take(4).forEachIndexed { idx, cat ->
                canvas.drawText("${idx + 1}. ${cat.category}", 60f, currentY, catNamePaint)
                canvas.drawText(
                    "Rs. ${String.format(Locale.getDefault(), "%,.0f", cat.amount)} (${String.format(Locale.getDefault(), "%.1f", cat.percentage)}%)",
                    1020f,
                    currentY,
                    catAmtPaint
                )

                // Background track
                val barTop = currentY + 16f
                val barBottom = barTop + 18f
                canvas.drawRoundRect(RectF(60f, barTop, 1020f, barBottom), 9f, 9f, barBgPaint)

                // Fill bar
                val fillWidth = (960f * (cat.percentage / 100f).toFloat()).coerceIn(12f, 960f)
                val fillPaint = Paint().apply {
                    color = Color.parseColor(colors[idx % colors.size])
                }
                canvas.drawRoundRect(RectF(60f, barTop, 60f + fillWidth, barBottom), 9f, 9f, fillPaint)

                currentY += 95f
            }
        }

        // Summary Statistics Footer Box
        val footerRect = RectF(60f, 1100f, 1020f, 1260f)
        canvas.drawRoundRect(footerRect, 18f, 18f, cardBgPaint)
        canvas.drawRoundRect(footerRect, 18f, 18f, cardBorder)

        val statLabelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#A0AEC0")
            textSize = 24f
            textAlign = Paint.Align.CENTER
        }
        val statValuePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#00E5FF")
            textSize = 36f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.CENTER
        }

        // Daily Avg
        canvas.drawText("DAILY AVERAGE", 300f, 1155f, statLabelPaint)
        canvas.drawText("Rs. ${String.format(Locale.getDefault(), "%,.0f", avgDailyExpense)}", 300f, 1215f, statValuePaint)

        // Divider
        canvas.drawLine(540f, 1130f, 540f, 1230f, cardBorder)

        // Tx Count
        canvas.drawText("TRANSACTIONS", 780f, 1155f, statLabelPaint)
        canvas.drawText("$txCount Records", 780f, 1215f, statValuePaint)

        // Save Bitmap to exports cache file
        val exportsDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val imageFile = File(exportsDir, "kharch_analytics_${System.currentTimeMillis()}.png")
        FileOutputStream(imageFile).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            out.flush()
        }

        return imageFile
    }

    private fun drawMetricBox(
        canvas: Canvas,
        rect: RectF,
        label: String,
        value: String,
        valueColor: Int,
        bgPaint: Paint,
        borderPaint: Paint
    ) {
        canvas.drawRoundRect(rect, 16f, 16f, bgPaint)
        canvas.drawRoundRect(rect, 16f, 16f, borderPaint)

        val labelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.parseColor("#94A3B8")
            textSize = 22f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        canvas.drawText(label, rect.left + 24f, rect.top + 46f, labelPaint)

        val valPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = valueColor
            textSize = 38f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        canvas.drawText(value, rect.left + 24f, rect.top + 105f, valPaint)
    }

    /**
     * Builds an Intent to share the visual image PNG file via WhatsApp or any system chooser.
     */
    fun createShareImageIntent(context: Context, imageFile: File, summaryText: String): Intent {
        val authority = "${context.packageName}.fileprovider"
        val contentUri: Uri = FileProvider.getUriForFile(context, authority, imageFile)

        return Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, contentUri)
            putExtra(Intent.EXTRA_TEXT, summaryText)
            putExtra(Intent.EXTRA_SUBJECT, "Kharch Financial Analytics")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }

    /**
     * Builds an Intent to share text summary directly (WhatsApp compatible).
     */
    fun createShareTextIntent(summaryText: String): Intent {
        return Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, summaryText)
            putExtra(Intent.EXTRA_SUBJECT, "Kharch Financial Analytics")
        }
    }

    /**
     * Copies summary to clipboard.
     */
    fun copyToClipboard(context: Context, text: String, label: String = "Kharch Analytics") {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText(label, text)
        clipboard.setPrimaryClip(clip)
    }
}
