package com.example.data.model

import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey

/**
 * Room Entity representing an Expense Category in the 'Track' feature.
 *
 * @param id Unique identifier auto-generated by Room.
 * @param name Name of the category (e.g. Food & Dining, Shopping, Transportation).
 * @param icon Icon key or identifier representing this category.
 * @param colorHex Hex color code string for visual identification in charts and UI.
 * @param budgetLimit Optional spending limit or budget allocated for this category.
 * @param isDefault Flag indicating whether this is a pre-defined system category.
 */
@Entity(tableName = "categories")
data class Category(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val name: String,
    val icon: String = "",
    val colorHex: String = "#10B981",
    val budgetLimit: Double? = null,
    val isDefault: Boolean = false
) {
    @Ignore
    constructor(name: String) : this(0L, name, "", "#10B981", null, false)

    @Ignore
    constructor(name: String, icon: String, colorHex: String) : this(0L, name, icon, colorHex, null, false)

    @Ignore
    constructor(id: Long, name: String) : this(id, name, "", "#10B981", null, false)

    @Ignore
    constructor(id: Int, name: String) : this(id.toLong(), name, "", "#10B981", null, false)

    companion object {
        val DEFAULT_CATEGORIES = listOf(
            Category(id = 1L, name = "Food & Dining", icon = "restaurant", colorHex = "#10B981", isDefault = true),
            Category(id = 2L, name = "Shopping", icon = "shopping_bag", colorHex = "#0284C7", isDefault = true),
            Category(id = 3L, name = "Transportation", icon = "directions_car", colorHex = "#6366F1", isDefault = true),
            Category(id = 4L, name = "Bills & Utilities", icon = "receipt_long", colorHex = "#F59E0B", isDefault = true),
            Category(id = 5L, name = "Entertainment", icon = "movie", colorHex = "#8B5CF6", isDefault = true),
            Category(id = 6L, name = "Health & Fitness", icon = "fitness_center", colorHex = "#F43F5E", isDefault = true),
            Category(id = 7L, name = "Education", icon = "school", colorHex = "#14B8A6", isDefault = true),
            Category(id = 8L, name = "Travel", icon = "flight", colorHex = "#F97316", isDefault = true),
            Category(id = 9L, name = "Groceries", icon = "local_grocery_store", colorHex = "#84CC16", isDefault = true),
            Category(id = 10L, name = "General", icon = "category", colorHex = "#64748B", isDefault = true)
        )
    }
}
