package com.example.data.model

import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room Entity representing an Expense transaction in the 'Track' feature.
 *
 * @param id Unique primary key auto-generated by Room.
 * @param amount The expense transaction amount.
 * @param category The category label of the expense.
 * @param date The timestamp/date of the transaction in milliseconds.
 * @param description Detailed description or note of the expense transaction.
 * @param categoryId Optional foreign identifier pointing to [Category.id].
 */
@Entity(
    tableName = "expenses",
    indices = [
        Index(value = ["categoryId"]),
        Index(value = ["date"]),
        Index(value = ["category"])
    ]
)
data class Expense(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val amount: Double,
    val category: String,
    val date: Long = System.currentTimeMillis(),
    val description: String = "",
    val categoryId: Long? = null
) {
    @Ignore
    constructor(amount: Double, category: String, date: Long, description: String) :
        this(0L, amount, category, date, description, null)

    @Ignore
    constructor(id: Int, amount: Double, category: String, date: Long, description: String) :
        this(id.toLong(), amount, category, date, description, null)

    @Ignore
    constructor(id: Long, amount: Double, category: String, date: Long, description: String) :
        this(id, amount, category, date, description, null)

    @Ignore
    constructor(amount: Double, category: String, date: Long, description: String, categoryId: Long?) :
        this(0L, amount, category, date, description, categoryId)
}
